//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiBrain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Racers = new HashSet<Racer>();
            this.VolunteerRecords = new HashSet<VolunteerRecord>();
        }
    
        public int Id { get; set; }
        public int TenantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Racer> Racers { get; set; }
        public virtual ICollection<VolunteerRecord> VolunteerRecords { get; set; }
    }
}
