//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiBrain.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkiDBEntities : DbContext
    {
        public SkiDBEntities()
            : base("name=SkiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Racer> Racers { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<MembershipType> MembershipTypes { get; set; }
        public virtual DbSet<VolunteerRecord> VolunteerRecords { get; set; }
        public virtual DbSet<VolunteerStatus> VolunteerStatuses { get; set; }
    }
}
