//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiBrain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.Racers = new HashSet<Racer>();
            this.Parents = new HashSet<Parent>();
            this.MembershipTypes = new HashSet<MembershipType>();
            this.VolunteerRecords = new HashSet<VolunteerRecord>();
            this.VolunteerStatus = new HashSet<VolunteerStatus>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Racer> Racers { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<MembershipType> MembershipTypes { get; set; }
        public virtual ICollection<VolunteerRecord> VolunteerRecords { get; set; }
        public virtual ICollection<VolunteerStatus> VolunteerStatus { get; set; }
    }
}
