//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiBrain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerRecord
    {
        public VolunteerRecord()
        {
            this.Parents = new HashSet<Parent>();
            this.Racers = new HashSet<Racer>();
            this.VolunteerStatus = new HashSet<VolunteerStatus>();
        }
    
        public int Id { get; set; }
        public int TenantId { get; set; }
        public string FamilyLastName { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<Racer> Racers { get; set; }
        public virtual ICollection<VolunteerStatus> VolunteerStatus { get; set; }
    }
}
